source 'https://rubygems.org'

gem 'rake'
gem 'dashing'
gem 'json', '~> 1.8.2'
gem 'dotenv'
gem 'octokit'
gem 'i18n'
gem 'faraday', '~> 0.9'
gem 'faraday-http-cache'
gem 'activesupport'
gem 'rspec'
gem 'rspec-mocks'
gem "sentry-raven", :git => "https://github.com/getsentry/raven-ruby.git"
gem 'typhoeus'
